services:
  api:
    build: .
    container_name: pizza-api
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_USER: t4_admin
      DB_PASSWORD: transport4
      DB_NAME: broncos_pizza_db
      DB_HOST: db
      DB_PORT: 5432
