version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: t4_admin
      POSTGRES_PASSWORD: transport4
      POSTGRES_DB: broncos_pizza_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: pizza-api
    depends_on:
      - db
    ports:
      - "3001:3000"
    environment:
      DB_USER: t4_admin
      DB_PASSWORD: transport4
      DB_NAME: broncos_pizza_db
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
